// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/RinTanth/go-backend/app/organization/access"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrganizationStorageMock creates a new instance of OrganizationStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationStorageMock {
	mock := &OrganizationStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrganizationStorageMock is an autogenerated mock type for the OrganizationStorage type
type OrganizationStorageMock struct {
	mock.Mock
}

type OrganizationStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationStorageMock) EXPECT() *OrganizationStorageMock_Expecter {
	return &OrganizationStorageMock_Expecter{mock: &_m.Mock}
}

// CreateOrganization provides a mock function for the type OrganizationStorageMock
func (_mock *OrganizationStorageMock) CreateOrganization(ctx context.Context, org access.Organization) (access.Organization, error) {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 access.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Organization) (access.Organization, error)); ok {
		return returnFunc(ctx, org)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Organization) access.Organization); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Get(0).(access.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.Organization) error); ok {
		r1 = returnFunc(ctx, org)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationStorageMock_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type OrganizationStorageMock_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - org access.Organization
func (_e *OrganizationStorageMock_Expecter) CreateOrganization(ctx interface{}, org interface{}) *OrganizationStorageMock_CreateOrganization_Call {
	return &OrganizationStorageMock_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, org)}
}

func (_c *OrganizationStorageMock_CreateOrganization_Call) Run(run func(ctx context.Context, org access.Organization)) *OrganizationStorageMock_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.Organization
		if args[1] != nil {
			arg1 = args[1].(access.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationStorageMock_CreateOrganization_Call) Return(organization access.Organization, err error) *OrganizationStorageMock_CreateOrganization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *OrganizationStorageMock_CreateOrganization_Call) RunAndReturn(run func(ctx context.Context, org access.Organization) (access.Organization, error)) *OrganizationStorageMock_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizationMember provides a mock function for the type OrganizationStorageMock
func (_mock *OrganizationStorageMock) CreateOrganizationMember(ctx context.Context, orgMember access.OrganizationMember) error {
	ret := _mock.Called(ctx, orgMember)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.OrganizationMember) error); ok {
		r0 = returnFunc(ctx, orgMember)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrganizationStorageMock_CreateOrganizationMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationMember'
type OrganizationStorageMock_CreateOrganizationMember_Call struct {
	*mock.Call
}

// CreateOrganizationMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgMember access.OrganizationMember
func (_e *OrganizationStorageMock_Expecter) CreateOrganizationMember(ctx interface{}, orgMember interface{}) *OrganizationStorageMock_CreateOrganizationMember_Call {
	return &OrganizationStorageMock_CreateOrganizationMember_Call{Call: _e.mock.On("CreateOrganizationMember", ctx, orgMember)}
}

func (_c *OrganizationStorageMock_CreateOrganizationMember_Call) Run(run func(ctx context.Context, orgMember access.OrganizationMember)) *OrganizationStorageMock_CreateOrganizationMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.OrganizationMember
		if args[1] != nil {
			arg1 = args[1].(access.OrganizationMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationStorageMock_CreateOrganizationMember_Call) Return(err error) *OrganizationStorageMock_CreateOrganizationMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrganizationStorageMock_CreateOrganizationMember_Call) RunAndReturn(run func(ctx context.Context, orgMember access.OrganizationMember) error) *OrganizationStorageMock_CreateOrganizationMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberOrganization provides a mock function for the type OrganizationStorageMock
func (_mock *OrganizationStorageMock) GetMemberOrganization(ctx context.Context, memberID uuid.UUID) (access.OrganizationMember, error) {
	ret := _mock.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberOrganization")
	}

	var r0 access.OrganizationMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (access.OrganizationMember, error)); ok {
		return returnFunc(ctx, memberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) access.OrganizationMember); ok {
		r0 = returnFunc(ctx, memberID)
	} else {
		r0 = ret.Get(0).(access.OrganizationMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationStorageMock_GetMemberOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberOrganization'
type OrganizationStorageMock_GetMemberOrganization_Call struct {
	*mock.Call
}

// GetMemberOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID uuid.UUID
func (_e *OrganizationStorageMock_Expecter) GetMemberOrganization(ctx interface{}, memberID interface{}) *OrganizationStorageMock_GetMemberOrganization_Call {
	return &OrganizationStorageMock_GetMemberOrganization_Call{Call: _e.mock.On("GetMemberOrganization", ctx, memberID)}
}

func (_c *OrganizationStorageMock_GetMemberOrganization_Call) Run(run func(ctx context.Context, memberID uuid.UUID)) *OrganizationStorageMock_GetMemberOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationStorageMock_GetMemberOrganization_Call) Return(organizationMember access.OrganizationMember, err error) *OrganizationStorageMock_GetMemberOrganization_Call {
	_c.Call.Return(organizationMember, err)
	return _c
}

func (_c *OrganizationStorageMock_GetMemberOrganization_Call) RunAndReturn(run func(ctx context.Context, memberID uuid.UUID) (access.OrganizationMember, error)) *OrganizationStorageMock_GetMemberOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationByID provides a mock function for the type OrganizationStorageMock
func (_mock *OrganizationStorageMock) GetOrganizationByID(ctx context.Context, organizationID uuid.UUID) (access.Organization, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 access.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (access.Organization, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) access.Organization); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		r0 = ret.Get(0).(access.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationStorageMock_GetOrganizationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationByID'
type OrganizationStorageMock_GetOrganizationByID_Call struct {
	*mock.Call
}

// GetOrganizationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID uuid.UUID
func (_e *OrganizationStorageMock_Expecter) GetOrganizationByID(ctx interface{}, organizationID interface{}) *OrganizationStorageMock_GetOrganizationByID_Call {
	return &OrganizationStorageMock_GetOrganizationByID_Call{Call: _e.mock.On("GetOrganizationByID", ctx, organizationID)}
}

func (_c *OrganizationStorageMock_GetOrganizationByID_Call) Run(run func(ctx context.Context, organizationID uuid.UUID)) *OrganizationStorageMock_GetOrganizationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationStorageMock_GetOrganizationByID_Call) Return(organization access.Organization, err error) *OrganizationStorageMock_GetOrganizationByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *OrganizationStorageMock_GetOrganizationByID_Call) RunAndReturn(run func(ctx context.Context, organizationID uuid.UUID) (access.Organization, error)) *OrganizationStorageMock_GetOrganizationByID_Call {
	_c.Call.Return(run)
	return _c
}
