// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/RinTanth/go-backend/app/member/access"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMemberStorageMock creates a new instance of MemberStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberStorageMock {
	mock := &MemberStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MemberStorageMock is an autogenerated mock type for the MemberStorage type
type MemberStorageMock struct {
	mock.Mock
}

type MemberStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberStorageMock) EXPECT() *MemberStorageMock_Expecter {
	return &MemberStorageMock_Expecter{mock: &_m.Mock}
}

// CreateMember provides a mock function for the type MemberStorageMock
func (_mock *MemberStorageMock) CreateMember(ctx context.Context, member access.Member) (access.Member, error) {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for CreateMember")
	}

	var r0 access.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Member) (access.Member, error)); ok {
		return returnFunc(ctx, member)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Member) access.Member); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Get(0).(access.Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.Member) error); ok {
		r1 = returnFunc(ctx, member)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemberStorageMock_CreateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMember'
type MemberStorageMock_CreateMember_Call struct {
	*mock.Call
}

// CreateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member access.Member
func (_e *MemberStorageMock_Expecter) CreateMember(ctx interface{}, member interface{}) *MemberStorageMock_CreateMember_Call {
	return &MemberStorageMock_CreateMember_Call{Call: _e.mock.On("CreateMember", ctx, member)}
}

func (_c *MemberStorageMock_CreateMember_Call) Run(run func(ctx context.Context, member access.Member)) *MemberStorageMock_CreateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.Member
		if args[1] != nil {
			arg1 = args[1].(access.Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemberStorageMock_CreateMember_Call) Return(member1 access.Member, err error) *MemberStorageMock_CreateMember_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MemberStorageMock_CreateMember_Call) RunAndReturn(run func(ctx context.Context, member access.Member) (access.Member, error)) *MemberStorageMock_CreateMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberById provides a mock function for the type MemberStorageMock
func (_mock *MemberStorageMock) GetMemberById(ctx context.Context, id uuid.UUID) (access.Member, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberById")
	}

	var r0 access.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (access.Member, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) access.Member); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(access.Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemberStorageMock_GetMemberById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberById'
type MemberStorageMock_GetMemberById_Call struct {
	*mock.Call
}

// GetMemberById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MemberStorageMock_Expecter) GetMemberById(ctx interface{}, id interface{}) *MemberStorageMock_GetMemberById_Call {
	return &MemberStorageMock_GetMemberById_Call{Call: _e.mock.On("GetMemberById", ctx, id)}
}

func (_c *MemberStorageMock_GetMemberById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MemberStorageMock_GetMemberById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemberStorageMock_GetMemberById_Call) Return(member access.Member, err error) *MemberStorageMock_GetMemberById_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MemberStorageMock_GetMemberById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (access.Member, error)) *MemberStorageMock_GetMemberById_Call {
	_c.Call.Return(run)
	return _c
}
