// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/RinTanth/go-backend/app/auth/access"
	"github.com/RinTanth/go-common/httpclient"
	mock "github.com/stretchr/testify/mock"
)

// NewGoogleClienterMock creates a new instance of GoogleClienterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleClienterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleClienterMock {
	mock := &GoogleClienterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoogleClienterMock is an autogenerated mock type for the GoogleClienter type
type GoogleClienterMock struct {
	mock.Mock
}

type GoogleClienterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleClienterMock) EXPECT() *GoogleClienterMock_Expecter {
	return &GoogleClienterMock_Expecter{mock: &_m.Mock}
}

// GetUserProfile provides a mock function for the type GoogleClienterMock
func (_mock *GoogleClienterMock) GetUserProfile(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleUserProfileResponse], error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 httpclient.Response[access.GoogleUserProfileResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (httpclient.Response[access.GoogleUserProfileResponse], error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) httpclient.Response[access.GoogleUserProfileResponse]); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(httpclient.Response[access.GoogleUserProfileResponse])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleClienterMock_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type GoogleClienterMock_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *GoogleClienterMock_Expecter) GetUserProfile(ctx interface{}, accessToken interface{}) *GoogleClienterMock_GetUserProfile_Call {
	return &GoogleClienterMock_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", ctx, accessToken)}
}

func (_c *GoogleClienterMock_GetUserProfile_Call) Run(run func(ctx context.Context, accessToken string)) *GoogleClienterMock_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoogleClienterMock_GetUserProfile_Call) Return(response httpclient.Response[access.GoogleUserProfileResponse], err error) *GoogleClienterMock_GetUserProfile_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GoogleClienterMock_GetUserProfile_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleUserProfileResponse], error)) *GoogleClienterMock_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type GoogleClienterMock
func (_mock *GoogleClienterMock) RevokeToken(ctx context.Context, accessToken string) (httpclient.Response[any], error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 httpclient.Response[any]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (httpclient.Response[any], error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) httpclient.Response[any]); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(httpclient.Response[any])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleClienterMock_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type GoogleClienterMock_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *GoogleClienterMock_Expecter) RevokeToken(ctx interface{}, accessToken interface{}) *GoogleClienterMock_RevokeToken_Call {
	return &GoogleClienterMock_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, accessToken)}
}

func (_c *GoogleClienterMock_RevokeToken_Call) Run(run func(ctx context.Context, accessToken string)) *GoogleClienterMock_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoogleClienterMock_RevokeToken_Call) Return(response httpclient.Response[any], err error) *GoogleClienterMock_RevokeToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GoogleClienterMock_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (httpclient.Response[any], error)) *GoogleClienterMock_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type GoogleClienterMock
func (_mock *GoogleClienterMock) ValidateAccessToken(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleTokenInfoResponse], error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 httpclient.Response[access.GoogleTokenInfoResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (httpclient.Response[access.GoogleTokenInfoResponse], error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) httpclient.Response[access.GoogleTokenInfoResponse]); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(httpclient.Response[access.GoogleTokenInfoResponse])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleClienterMock_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type GoogleClienterMock_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *GoogleClienterMock_Expecter) ValidateAccessToken(ctx interface{}, accessToken interface{}) *GoogleClienterMock_ValidateAccessToken_Call {
	return &GoogleClienterMock_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, accessToken)}
}

func (_c *GoogleClienterMock_ValidateAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *GoogleClienterMock_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoogleClienterMock_ValidateAccessToken_Call) Return(response httpclient.Response[access.GoogleTokenInfoResponse], err error) *GoogleClienterMock_ValidateAccessToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GoogleClienterMock_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleTokenInfoResponse], error)) *GoogleClienterMock_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostgresRepoerMock creates a new instance of PostgresRepoerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgresRepoerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostgresRepoerMock {
	mock := &PostgresRepoerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostgresRepoerMock is an autogenerated mock type for the PostgresRepoer type
type PostgresRepoerMock struct {
	mock.Mock
}

type PostgresRepoerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PostgresRepoerMock) EXPECT() *PostgresRepoerMock_Expecter {
	return &PostgresRepoerMock_Expecter{mock: &_m.Mock}
}

// GetUserByEmail provides a mock function for the type PostgresRepoerMock
func (_mock *PostgresRepoerMock) GetUserByEmail(ctx context.Context, hashedEmail string) (access.User, error) {
	ret := _mock.Called(ctx, hashedEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 access.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.User, error)); ok {
		return returnFunc(ctx, hashedEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.User); ok {
		r0 = returnFunc(ctx, hashedEmail)
	} else {
		r0 = ret.Get(0).(access.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashedEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresRepoerMock_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type PostgresRepoerMock_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedEmail string
func (_e *PostgresRepoerMock_Expecter) GetUserByEmail(ctx interface{}, hashedEmail interface{}) *PostgresRepoerMock_GetUserByEmail_Call {
	return &PostgresRepoerMock_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, hashedEmail)}
}

func (_c *PostgresRepoerMock_GetUserByEmail_Call) Run(run func(ctx context.Context, hashedEmail string)) *PostgresRepoerMock_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PostgresRepoerMock_GetUserByEmail_Call) Return(user access.User, err error) *PostgresRepoerMock_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *PostgresRepoerMock_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, hashedEmail string) (access.User, error)) *PostgresRepoerMock_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}
