// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/RinTanth/go-backend/app/auth/access"
	"github.com/RinTanth/go-common/httpclient"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewGoogleClientMock creates a new instance of GoogleClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleClientMock {
	mock := &GoogleClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoogleClientMock is an autogenerated mock type for the GoogleClient type
type GoogleClientMock struct {
	mock.Mock
}

type GoogleClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleClientMock) EXPECT() *GoogleClientMock_Expecter {
	return &GoogleClientMock_Expecter{mock: &_m.Mock}
}

// GetUserProfile provides a mock function for the type GoogleClientMock
func (_mock *GoogleClientMock) GetUserProfile(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleUserProfileResponse], error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 httpclient.Response[access.GoogleUserProfileResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (httpclient.Response[access.GoogleUserProfileResponse], error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) httpclient.Response[access.GoogleUserProfileResponse]); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(httpclient.Response[access.GoogleUserProfileResponse])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleClientMock_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type GoogleClientMock_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *GoogleClientMock_Expecter) GetUserProfile(ctx interface{}, accessToken interface{}) *GoogleClientMock_GetUserProfile_Call {
	return &GoogleClientMock_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", ctx, accessToken)}
}

func (_c *GoogleClientMock_GetUserProfile_Call) Run(run func(ctx context.Context, accessToken string)) *GoogleClientMock_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoogleClientMock_GetUserProfile_Call) Return(response httpclient.Response[access.GoogleUserProfileResponse], err error) *GoogleClientMock_GetUserProfile_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GoogleClientMock_GetUserProfile_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleUserProfileResponse], error)) *GoogleClientMock_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type GoogleClientMock
func (_mock *GoogleClientMock) RevokeToken(ctx context.Context, accessToken string) (httpclient.Response[any], error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 httpclient.Response[any]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (httpclient.Response[any], error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) httpclient.Response[any]); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(httpclient.Response[any])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleClientMock_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type GoogleClientMock_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *GoogleClientMock_Expecter) RevokeToken(ctx interface{}, accessToken interface{}) *GoogleClientMock_RevokeToken_Call {
	return &GoogleClientMock_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, accessToken)}
}

func (_c *GoogleClientMock_RevokeToken_Call) Run(run func(ctx context.Context, accessToken string)) *GoogleClientMock_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoogleClientMock_RevokeToken_Call) Return(response httpclient.Response[any], err error) *GoogleClientMock_RevokeToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GoogleClientMock_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (httpclient.Response[any], error)) *GoogleClientMock_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type GoogleClientMock
func (_mock *GoogleClientMock) ValidateAccessToken(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleTokenInfoResponse], error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 httpclient.Response[access.GoogleTokenInfoResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (httpclient.Response[access.GoogleTokenInfoResponse], error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) httpclient.Response[access.GoogleTokenInfoResponse]); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(httpclient.Response[access.GoogleTokenInfoResponse])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleClientMock_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type GoogleClientMock_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *GoogleClientMock_Expecter) ValidateAccessToken(ctx interface{}, accessToken interface{}) *GoogleClientMock_ValidateAccessToken_Call {
	return &GoogleClientMock_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, accessToken)}
}

func (_c *GoogleClientMock_ValidateAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *GoogleClientMock_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoogleClientMock_ValidateAccessToken_Call) Return(response httpclient.Response[access.GoogleTokenInfoResponse], err error) *GoogleClientMock_ValidateAccessToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GoogleClientMock_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (httpclient.Response[access.GoogleTokenInfoResponse], error)) *GoogleClientMock_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberStorageMock creates a new instance of MemberStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberStorageMock {
	mock := &MemberStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MemberStorageMock is an autogenerated mock type for the MemberStorage type
type MemberStorageMock struct {
	mock.Mock
}

type MemberStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberStorageMock) EXPECT() *MemberStorageMock_Expecter {
	return &MemberStorageMock_Expecter{mock: &_m.Mock}
}

// GetMemberByEmail provides a mock function for the type MemberStorageMock
func (_mock *MemberStorageMock) GetMemberByEmail(ctx context.Context, hashedEmail string) (access.Member, error) {
	ret := _mock.Called(ctx, hashedEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberByEmail")
	}

	var r0 access.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Member, error)); ok {
		return returnFunc(ctx, hashedEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Member); ok {
		r0 = returnFunc(ctx, hashedEmail)
	} else {
		r0 = ret.Get(0).(access.Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashedEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemberStorageMock_GetMemberByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberByEmail'
type MemberStorageMock_GetMemberByEmail_Call struct {
	*mock.Call
}

// GetMemberByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedEmail string
func (_e *MemberStorageMock_Expecter) GetMemberByEmail(ctx interface{}, hashedEmail interface{}) *MemberStorageMock_GetMemberByEmail_Call {
	return &MemberStorageMock_GetMemberByEmail_Call{Call: _e.mock.On("GetMemberByEmail", ctx, hashedEmail)}
}

func (_c *MemberStorageMock_GetMemberByEmail_Call) Run(run func(ctx context.Context, hashedEmail string)) *MemberStorageMock_GetMemberByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemberStorageMock_GetMemberByEmail_Call) Return(member access.Member, err error) *MemberStorageMock_GetMemberByEmail_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MemberStorageMock_GetMemberByEmail_Call) RunAndReturn(run func(ctx context.Context, hashedEmail string) (access.Member, error)) *MemberStorageMock_GetMemberByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationStorageMock creates a new instance of OrganizationStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationStorageMock {
	mock := &OrganizationStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrganizationStorageMock is an autogenerated mock type for the OrganizationStorage type
type OrganizationStorageMock struct {
	mock.Mock
}

type OrganizationStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationStorageMock) EXPECT() *OrganizationStorageMock_Expecter {
	return &OrganizationStorageMock_Expecter{mock: &_m.Mock}
}

// GetMemberOrganization provides a mock function for the type OrganizationStorageMock
func (_mock *OrganizationStorageMock) GetMemberOrganization(ctx context.Context, memberID uuid.UUID) (access.OrganizationMember, error) {
	ret := _mock.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberOrganization")
	}

	var r0 access.OrganizationMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (access.OrganizationMember, error)); ok {
		return returnFunc(ctx, memberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) access.OrganizationMember); ok {
		r0 = returnFunc(ctx, memberID)
	} else {
		r0 = ret.Get(0).(access.OrganizationMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationStorageMock_GetMemberOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberOrganization'
type OrganizationStorageMock_GetMemberOrganization_Call struct {
	*mock.Call
}

// GetMemberOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID uuid.UUID
func (_e *OrganizationStorageMock_Expecter) GetMemberOrganization(ctx interface{}, memberID interface{}) *OrganizationStorageMock_GetMemberOrganization_Call {
	return &OrganizationStorageMock_GetMemberOrganization_Call{Call: _e.mock.On("GetMemberOrganization", ctx, memberID)}
}

func (_c *OrganizationStorageMock_GetMemberOrganization_Call) Run(run func(ctx context.Context, memberID uuid.UUID)) *OrganizationStorageMock_GetMemberOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationStorageMock_GetMemberOrganization_Call) Return(organizationMember access.OrganizationMember, err error) *OrganizationStorageMock_GetMemberOrganization_Call {
	_c.Call.Return(organizationMember, err)
	return _c
}

func (_c *OrganizationStorageMock_GetMemberOrganization_Call) RunAndReturn(run func(ctx context.Context, memberID uuid.UUID) (access.OrganizationMember, error)) *OrganizationStorageMock_GetMemberOrganization_Call {
	_c.Call.Return(run)
	return _c
}
